#!/usr/bin/env python3
"""NescioAI brand mark: a geometric little owl (noctua), plus derived assets.

Pure string generation — stdlib only, no Pillow, no Chromium and **no
fontTools**. Safe in CI.

Colours come from `brand.palette`; this module declares none of its own. That
retires the brand half of the palette drift the package exists to end (a second
near-black doing the job of `palette.text`, and an inline grey on the size
sheet doing the job of `palette.muted`).

The wordmark is outlined
-------------------------
"nescio" used to be live `<text>` in a mono face. Almost nothing on the open
web has that font installed — including the servers that render link previews —
so the social card was at risk of rendering the wordmark in whatever fallback
the renderer happened to reach for. Spec `docs/design/design-system.md` §3 calls
for outlining it, and `WORDMARK_PATH` below is that outline: real glyph
contours, in font units, immune to the font decision.

`WORDMARK_PATH` is **baked in as a constant** so that running this script needs
nothing but the stdlib. It is regenerated by an opt-in step that imports
fontTools lazily, inside a function, and is never reached on a normal run:

    python -m venv /tmp/ftvenv                       # local-only tooling,
    /tmp/ftvenv/bin/python -m pip install fonttools  # not a repo dependency
    /tmp/ftvenv/bin/python brand/make_brand.py --print-wordmark-path

That prints `upm`, the total advance and the `d` attribute; paste them into
`WORDMARK_UPM`, `WORDMARK_ADVANCE` and `WORDMARK_PATH`. Task T16 re-runs it
against IBM Plex Mono when that migration lands — the source font is the single
constant `WORDMARK_SOURCE`.

**Why Bold and not Regular.** Both call sites set the wordmark at `weight=700`,
so the live text they replaced rendered in Liberation Mono *Bold*; outlining
from Regular would silently thin the wordmark. Liberation Mono is monospaced
and carries no kerning, so the two weights are metrically identical (advance
7374/2048 em for the six glyphs) — only the stem weight differs. Both `.ttf`s
are committed under `brand/fonts/`.

Output directory, highest precedence first:
  1. ``--out DIR``
  2. ``$BRAND_OUT``
  3. ``<this file's directory>/dist`` — i.e. ``brand/dist/``, resolved relative
     to this file, not the current working directory.
"""
import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from brand import palette  # noqa: E402

FONT = palette.FONT_SANS
MONO = palette.FONT_MONO


def _n(v):
    """Compact SVG number: no trailing zeros, no exponent at our magnitudes."""
    return f"{v:.6g}"


def owl(color=palette.brand_blue, eye=palette.paper, pupil=palette.brand_blue,
        scale=1.0, dx=0, dy=0, pupil_shift=0):
    """The mark, drawn on a nominal 512x512 grid."""
    head = ("M 140 112 "
            "C 160 168 176 176 186 186 "
            "Q 256 152 326 186 "
            "C 336 176 352 168 372 112 "
            "C 394 172 402 262 380 314 "
            "C 350 384 306 408 256 408 "
            "C 206 408 162 384 132 314 "
            "C 110 262 118 172 140 112 Z")
    g = [f'<g transform="translate({dx},{dy}) scale({scale})">']
    g.append(f'<path d="{head}" fill="{color}"/>')
    for cx in (202, 310):
        g.append(f'<circle cx="{cx}" cy="248" r="49" fill="{eye}"/>')
        g.append(f'<circle cx="{cx + pupil_shift}" cy="248" r="21" fill="{pupil}"/>')
    # beak: a small chevron, pointing down
    g.append(f'<path d="M 256 296 L 274 318 L 256 340 L 238 318 Z" fill="{eye}"/>')
    g.append("</g>")
    return "".join(g)


def svg(w, h, body, bg=None):
    b = f'<rect width="{w}" height="{h}" fill="{bg}"/>' if bg else ""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{w}" height="{h}" '
            f'viewBox="0 0 {w} {h}">{b}{body}</svg>')


def text(x, y, s, size=16, fill=palette.text, weight="400", anchor="start",
         family=FONT, spacing=None):
    sp = f' letter-spacing="{spacing}"' if spacing else ""
    return (f'<text x="{x}" y="{y}" font-family="{family}" font-size="{size}" '
            f'fill="{fill}" font-weight="{weight}" text-anchor="{anchor}"{sp}>{s}</text>')


# --- the outlined wordmark --------------------------------------------------
#
# Glyph contours for "nescio", laid out left to right at their advance widths
# (the face is monospaced and has no `kern` table and no GPOS `kern` feature,
# so advances are the whole of the letterfit). Coordinates are raw font units
# with y pointing **up**, exactly as they come out of the font; `wordmark()`
# supplies the flip and the scale. Regenerate with --print-wordmark-path.

WORDMARK_TEXT = "nescio"
WORDMARK_SOURCE = "fonts/LiberationMono-Bold.ttf"  # relative to this file
WORDMARK_UPM = 2048  # units per em of the source face
WORDMARK_ADVANCE = 7374  # total advance of WORDMARK_TEXT, in font units
WORDMARK_PATH = (
    "M824 0V619Q824 760 786 826Q747 892 653 892Q549 892 486 804Q424 715 424"
    " 580V0H143V840Q143 927 140 982Q138 1038 135 1082H403Q406 1063 411 "
    "980Q416 898 416 867H420Q477 991 563 1047Q649 1103 768 1103Q1104 1103 "
    "1104 687V0ZM1855 -20Q1603 -20 1466 128Q1329 277 1329 546Q1329 726 1394"
    " 850Q1458 974 1577 1038Q1696 1102 1859 1102Q2096 1102 2227 944Q2358 "
    "786 2358 495V487H1624Q1624 340 1690 254Q1755 168 1869 168Q1943 168 "
    "2000 200Q2057 231 2077 297L2342 274Q2287 133 2159 56Q2031 -20 1855 "
    "-20ZM1855 925Q1752 925 1691 856Q1630 786 1626 663H2086Q2079 783 2018 "
    "854Q1956 925 1855 925ZM3562 316Q3562 159 3434 70Q3305 -20 3078 "
    "-20Q2855 -20 2736 50Q2618 121 2579 270L2826 307Q2847 230 2898 198Q2950"
    " 166 3078 166Q3196 166 3250 196Q3304 226 3304 290Q3304 342 3260 "
    "372Q3217 403 3113 424Q2875 471 2792 512Q2709 552 2666 616Q2622 681 "
    "2622 775Q2622 930 2742 1016Q2861 1103 3080 1103Q3273 1103 3390 "
    "1028Q3508 953 3537 811L3288 785Q3276 851 3229 884Q3182 916 3080 "
    "916Q2980 916 2930 890Q2880 865 2880 805Q2880 758 2918 730Q2957 703 "
    "3048 685Q3175 659 3274 632Q3372 604 3432 566Q3491 528 3526 468Q3562 "
    "409 3562 316ZM4311 -20Q4065 -20 3931 126Q3797 273 3797 535Q3797 803 "
    "3932 952Q4067 1102 4315 1102Q4506 1102 4631 1006Q4756 910 4788 "
    "741L4505 727Q4493 810 4445 860Q4397 909 4309 909Q4092 909 4092 "
    "546Q4092 172 4313 172Q4393 172 4447 222Q4501 273 4514 373L4796 "
    "360Q4781 249 4716 162Q4652 75 4547 28Q4442 -20 4311 -20ZM5710 "
    "190H6063V0H5034V190H5429V892H5139V1082H5710ZM5429 "
    "1277V1484H5710V1277ZM7282 542Q7282 273 7146 126Q7010 -20 6755 -20Q6509"
    " -20 6373 126Q6237 273 6237 542Q6237 810 6372 956Q6507 1102 6761 "
    "1102Q7282 1102 7282 542ZM6988 542Q6988 734 6937 822Q6886 909 6765 "
    "909Q6641 909 6586 821Q6532 733 6532 542Q6532 349 6588 260Q6643 172 "
    "6752 172Q6876 172 6932 260Q6988 347 6988 542Z"
)


def wordmark_width(size):
    """Rendered width of the wordmark at `size`, in user units.

    Identical to the advance width the live `<text>` element occupied, which is
    what makes `anchor="middle"` land in the same place as `text-anchor`.
    """
    return WORDMARK_ADVANCE * size / WORDMARK_UPM


def wordmark(x, y, size, fill, anchor="start"):
    """The wordmark as `<path>` outlines.

    `x`/`y` are the text origin — `y` is the baseline, and `anchor` mirrors
    SVG's `text-anchor`, so this is a drop-in replacement for the `<text>`
    element it supersedes.
    """
    s = size / WORDMARK_UPM
    width = wordmark_width(size)
    ox = {"start": x, "middle": x - width / 2, "end": x - width}[anchor]
    return (f'<path transform="translate({_n(ox)},{_n(y)}) '
            f'scale({_n(s)},{_n(-s)})" d="{WORDMARK_PATH}" fill="{fill}"/>')


def build_wordmark_outline(font_path=None, string=WORDMARK_TEXT):
    """Re-derive (upm, advance, path) from the source font. **Local-only.**

    Imports fontTools *inside the function* on purpose: `make_brand.py` must
    stay stdlib-only on a normal run so CI never grows a font dependency. This
    is reached only via `--print-wordmark-path`.
    """
    from fontTools.pens.svgPathPen import SVGPathPen  # noqa: PLC0415
    from fontTools.pens.transformPen import TransformPen  # noqa: PLC0415
    from fontTools.ttLib import TTFont  # noqa: PLC0415

    path = Path(font_path) if font_path else Path(__file__).resolve().parent / WORDMARK_SOURCE
    font = TTFont(path)
    upm = font["head"].unitsPerEm
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    hmtx = font["hmtx"]
    # Legacy `kern` if present; this face has none, but a later source face
    # (T16's IBM Plex Mono) might, and the letterfit must respect it.
    kern_tables = font["kern"].kernTables if "kern" in font else []

    pieces, x, previous = [], 0, None
    for ch in string:
        name = cmap[ord(ch)]
        if previous is not None:
            for table in kern_tables:
                x += table.kernTable.get((previous, name), 0)
        pen = SVGPathPen(glyphs, ntos=lambda v: str(int(round(v))))
        glyphs[name].draw(TransformPen(pen, (1, 0, 0, 1, x, 0)))
        drawn = pen.getCommands()
        if drawn:
            pieces.append(drawn)
        x += hmtx[name][0]
        previous = name
    return upm, x, "".join(pieces)


# --- 1. the bare mark -------------------------------------------------------
mark = svg(512, 512, owl())

# --- 2. badge (rounded square, for avatars) ---------------------------------
badge = svg(512, 512,
            f'<rect width="512" height="512" rx="112" fill="{palette.brand_blue}"/>'
            + owl(color=palette.paper, eye=palette.brand_blue, pupil=palette.paper,
                  scale=0.78, dx=56, dy=56))

# --- 3. GitHub social preview, 1280x640 -------------------------------------
sp = [f'<rect width="1280" height="640" fill="{palette.ink_deep}"/>']
sp.append(f'<circle cx="1150" cy="120" r="420" fill="{palette.ink_raised}"/>')
sp.append(owl(color=palette.periwinkle, eye=palette.ink_deep, pupil=palette.periwinkle,
              scale=0.52, dx=96, dy=176))
sp.append(wordmark(392, 300, 104, palette.paper))
sp.append(text(392, 356, "an agent crew for Claude Code", size=30,
               fill=palette.muted_dark))
sp.append(f'<rect x="392" y="392" width="86" height="3" fill="{palette.periwinkle}"/>')
sp.append(text(392, 452, "&#8220;I don&#8217;t know&#8221; is a first-class answer.",
               size=34, fill=palette.periwinkle))
sp.append(text(392, 500, "github.com/noctua84/nescio-ai", size=24,
               fill=palette.muted_dark, family=MONO))
social = svg(1280, 640, "".join(sp))

# --- 4. Medium cover, 1500x750 ----------------------------------------------
mc = [f'<rect width="1500" height="750" fill="{palette.ink_deep}"/>']
for i in range(9):
    x = 150 + i * 150
    mc.append(f'<circle cx="{x}" cy="690" r="3" fill="{palette.tint_dark}"/>')
mc.append(owl(color=palette.periwinkle, eye=palette.ink_deep, pupil=palette.periwinkle,
              scale=0.58, dx=602, dy=140))
mc.append(wordmark(750, 470, 76, palette.paper, anchor="middle"))
mc.append(text(750, 522, "an agent is allowed to say &#8220;I don&#8217;t know&#8221;",
               size=30, fill=palette.muted_dark, anchor="middle"))
cover = svg(1500, 750, "".join(mc))

# --- 5. legibility contact sheet --------------------------------------------
cs = [f'<rect width="900" height="300" fill="{palette.paper}"/>']
x = 80
for px in (128, 64, 48, 32, 24, 16):
    s = px / 512
    cs.append(f'<g transform="translate({x},{150 - px / 2})">'
              + owl(scale=s) + "</g>")
    cs.append(text(x + px / 2, 220, f"{px}px", size=13, fill=palette.muted,
                   anchor="middle"))
    x += px + 56
cs.append(text(80, 60, "Legibility check — the mark must survive the avatar size",
               size=17, fill=palette.text, weight="700"))
sheet = svg(900, 300, "".join(cs))

ASSETS = [("logo-mark", mark), ("logo-badge", badge),
          ("github-social", social), ("medium-cover", cover),
          ("logo-sizes", sheet)]


def _parser():
    ap = argparse.ArgumentParser(description="Generate the NescioAI brand SVGs.")
    ap.add_argument("--out", default=os.environ.get("BRAND_OUT"),
                    help="output directory (default: $BRAND_OUT, else brand/dist/)")
    ap.add_argument("--font", default=None,
                    help="source font for --print-wordmark-path "
                         f"(default: brand/{WORDMARK_SOURCE})")
    ap.add_argument("--print-wordmark-path", action="store_true",
                    help="re-derive the outlined wordmark from the source font "
                         "and print it; needs fontTools, writes nothing")
    return ap


def resolve_out_dir(argv=None):
    """--out, else $BRAND_OUT, else brand/dist/ next to this file."""
    return _out_dir(_parser().parse_args(argv))


def _out_dir(args):
    out = (Path(args.out).expanduser() if args.out
           else Path(__file__).resolve().parent / "dist")
    out.mkdir(parents=True, exist_ok=True)
    return out


def write(path, content):
    """Write UTF-8 with LF endings, so output is byte-identical on any OS."""
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(content)


if __name__ == "__main__":
    ARGS = _parser().parse_args()
    if ARGS.print_wordmark_path:
        UPM, ADVANCE, PATH_D = build_wordmark_outline(ARGS.font)
        print(f"WORDMARK_UPM = {UPM}")
        print(f"WORDMARK_ADVANCE = {ADVANCE}")
        print(f"WORDMARK_PATH = {PATH_D!r}")
    else:
        OUT_DIR = _out_dir(ARGS)
        for name, content in ASSETS:
            write(OUT_DIR / f"nescio-{name}.svg", content)
        print(f"brand svgs written -> {OUT_DIR}")
