# brand/test_diagrams.py
"""Tests for the tokenised diagram generator.

These live in `brand/`, NOT in `tests/`, on purpose. `tests` is on
`FRAMEWORK_PATHS` in `scripts/sync_from_upstream.py` and is copied into every
derived instance; `brand/` deliberately is not. A `tests/` module importing
`brand` would crash `python -m unittest` for every downstream user.

    python -m unittest brand.test_diagrams     # from the repo root

What is asserted, in the words of spec §6:

  - the source carries no ground `<rect>` and no hardcoded hex outside its
    `<style>` defaults block;
  - the twins carry no `var(`;
  - every colour in a twin is the §6 table's value for that twin's column —
    checked against a literal transcription of the table, not the generator's
    own constants;
  - `#8a919b` (3.2:1 on white, retired by §2) appears nowhere.
"""

import re
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from brand import make_diagrams as md  # noqa: E402
from brand import palette  # noqa: E402

# Spec §2: `#8a919b` measured 3.2:1 on white and carried every section label,
# connector label and deferred annotation in both diagrams before this task.
RETIRED = "#8a919b"

# Spec §6, "Diagram tokens", transcribed by hand. This is the authority these
# tests check against — deliberately *not* imported from the generator, so a
# wrong edit to the generator's own tables fails here.
SPEC_SIX = {
    # element                      light        dark
    "emphasised node fill":       ("#eef2f8", "#182333"),
    "emphasised node stroke":     ("#2f4d7a", "#8fb0d9"),
    "plain node fill":            ("#ffffff", "#141b24"),
    "plain node stroke":          ("#c9cfd8", "#26313f"),
    "plain node label":           ("#16191f", "#e9edf2"),
    "body text":                  ("#5a616b", "#a8b0ba"),
    "caption / connector label":  ("#6b727c", "#8d97a4"),
    "connector":                  ("#c9cfd8", "#26313f"),
    "accent connector":           ("#2f4d7a", "#8fb0d9"),
    "deferred (dashed)":          ("#a8b0ba", "#a8b0ba"),
}

VAR_TO_SPEC_ROW = {
    "--diagram-accent-fill": "emphasised node fill",
    "--diagram-accent": "emphasised node stroke",
    "--diagram-node-fill": "plain node fill",
    "--diagram-node-stroke": "plain node stroke",
    "--diagram-node-label": "plain node label",
    "--diagram-body": "body text",
    "--diagram-muted": "caption / connector label",
    "--diagram-connector": "connector",
    "--diagram-accent-connector": "accent connector",
    "--diagram-deferred": "deferred (dashed)",
}

COLOUR_ATTR_RE = re.compile(r'(?:fill|stroke)="([^"]+)"')
HEX_RE = re.compile(r"#[0-9a-fA-F]{3,8}")
STYLE_RE = re.compile(r"<style>.*?</style>", re.DOTALL)
# The ground the old generator emitted: a rect covering the whole canvas, with
# no x/y and no rx — structurally distinct from every node box.
GROUND_RECT_RE = re.compile(r'<rect\s+width=')

SOURCES = {name: make() for name, make in md.DIAGRAMS.items()}
TWINS = {
    (name, scheme): md.resolve(svg, scheme)
    for name, svg in SOURCES.items()
    for scheme in ("light", "dark")
}


class TestRetiredHex(unittest.TestCase):
    """The WCAG AA fix, asserted on the generated bytes."""

    def test_absent_from_every_output(self):
        for name, svg in SOURCES.items():
            with self.subTest(file=f"{name}.svg"):
                self.assertNotIn(RETIRED, svg.lower())
        for (name, scheme), svg in TWINS.items():
            with self.subTest(file=f"{name}-{scheme}.svg"):
                self.assertNotIn(RETIRED, svg.lower())

    def test_never_a_literal_in_the_generator_module(self):
        """The docstring names it as the bug it fixed; nothing may *use* it."""
        source = Path(md.__file__).read_text(encoding="utf-8").lower()
        self.assertNotIn(f'"{RETIRED}"', source)
        self.assertNotIn(f"'{RETIRED}'", source)

    def test_absent_from_both_resolution_tables(self):
        for scheme, table in (("light", md.LIGHT), ("dark", md.DARK)):
            for var, value in table.items():
                with self.subTest(scheme=scheme, var=var):
                    self.assertNotEqual(RETIRED, value.lower())

    def test_the_muted_token_that_replaced_it_passes_aa(self):
        self.assertGreaterEqual(
            palette.contrast_ratio(md.LIGHT["--diagram-muted"], palette.paper), 4.5
        )
        self.assertGreaterEqual(
            palette.contrast_ratio(md.DARK["--diagram-muted"], palette.ink_deep), 4.5
        )


class TestTokenisedSource(unittest.TestCase):
    """Spec §6 authoring rules: no ground, no hardcoded fills."""

    def test_no_background_rect(self):
        for name, svg in SOURCES.items():
            with self.subTest(file=name):
                self.assertIsNone(GROUND_RECT_RE.search(svg))

    def test_no_hardcoded_hex_outside_the_style_block(self):
        for name, svg in SOURCES.items():
            with self.subTest(file=name):
                self.assertEqual([], HEX_RE.findall(STYLE_RE.sub("", svg)))

    def test_every_colour_attribute_is_a_var_or_none(self):
        for name, svg in SOURCES.items():
            body = STYLE_RE.sub("", svg)
            for value in COLOUR_ATTR_RE.findall(body):
                with self.subTest(file=name, value=value):
                    self.assertTrue(
                        value == "none" or value.startswith("var(--diagram-"),
                        f"{value!r} is neither a diagram token nor `none`",
                    )

    def test_declares_defaults_for_every_var_it_uses(self):
        declared = set(md.LIGHT)
        for name, svg in SOURCES.items():
            used = set(re.findall(r"var\((--[a-z0-9-]+)\)", svg))
            with self.subTest(file=name):
                self.assertTrue(used, "the source uses no tokens at all")
                self.assertEqual(set(), used - declared)

    def test_defaults_are_scoped_to_svg_root(self):
        """Bare `svg {}` would beat an inlining page's tokens and kill the toggle."""
        for name, svg in SOURCES.items():
            with self.subTest(file=name):
                self.assertIn("svg:root {", svg)

    def test_fonts_come_from_the_palette(self):
        for name, svg in SOURCES.items():
            with self.subTest(file=name):
                self.assertIn(f'font-family="{palette.FONT_SANS}"', svg)
                self.assertIn(f'font-family="{palette.FONT_MONO}"', svg)


class TestTwins(unittest.TestCase):
    """Spec §6 pipeline: concrete hexes for consumers with no CSS variables."""

    def test_no_var_remains(self):
        for (name, scheme), svg in TWINS.items():
            with self.subTest(file=f"{name}-{scheme}"):
                self.assertNotIn("var(", svg)
                self.assertNotIn("--diagram-", svg)

    def test_style_block_is_gone(self):
        for (name, scheme), svg in TWINS.items():
            with self.subTest(file=f"{name}-{scheme}"):
                self.assertNotIn("<style>", svg)

    def test_carries_a_ground(self):
        """The twins exist for bare `<img>` consumers, which supply nothing."""
        for (name, scheme), svg in TWINS.items():
            with self.subTest(file=f"{name}-{scheme}"):
                self.assertIsNotNone(GROUND_RECT_RE.search(svg))
                self.assertIn(f'fill="{md.GROUND[scheme]}"', svg)

    def test_every_colour_is_in_the_spec_six_column(self):
        for scheme, index in (("light", 0), ("dark", 1)):
            allowed = {row[index] for row in SPEC_SIX.values()}
            allowed.add(md.GROUND[scheme])
            for (name, sch), svg in TWINS.items():
                if sch != scheme:
                    continue
                for value in COLOUR_ATTR_RE.findall(svg):
                    with self.subTest(file=f"{name}-{scheme}", value=value):
                        self.assertTrue(
                            value == "none" or value.lower() in allowed,
                            f"{value!r} is not a spec §6 {scheme}-column colour",
                        )

    def test_geometry_is_unchanged_by_resolution(self):
        """Only colours and the ground differ between source and twin."""
        for (name, scheme), svg in TWINS.items():
            with self.subTest(file=f"{name}-{scheme}"):
                self.assertEqual(
                    SOURCES[name].count("<path"), svg.count("<path")
                )
                self.assertEqual(
                    SOURCES[name].count("<text"), svg.count("<text")
                )
                # one extra rect: the ground
                self.assertEqual(
                    SOURCES[name].count("<rect") + 1, svg.count("<rect")
                )

    def test_unknown_scheme_rejected(self):
        with self.assertRaises(ValueError):
            md.resolve(SOURCES["diagram-crew"], "sepia")


class TestResolutionTables(unittest.TestCase):
    """The generator's own tables against the §6 transcription."""

    def test_light_matches_spec_six(self):
        for var, row in VAR_TO_SPEC_ROW.items():
            with self.subTest(var=var):
                self.assertEqual(md.LIGHT[var], SPEC_SIX[row][0])

    def test_dark_matches_spec_six(self):
        for var, row in VAR_TO_SPEC_ROW.items():
            with self.subTest(var=var):
                self.assertEqual(md.DARK[var], SPEC_SIX[row][1])

    def test_both_tables_cover_exactly_the_expected_vars(self):
        self.assertEqual(set(md.LIGHT), set(VAR_TO_SPEC_ROW))
        self.assertEqual(set(md.DARK), set(VAR_TO_SPEC_ROW))

    def test_grounds_are_canonical_page_grounds(self):
        self.assertEqual(md.GROUND["light"], palette.paper)
        self.assertEqual(md.GROUND["dark"], palette.ink_deep)


class TestBuild(unittest.TestCase):
    def test_writes_six_files_with_lf_endings(self):
        import tempfile

        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp)
            written = md.build(out)
            self.assertEqual(6, len(written))
            names = sorted(p.name for p in written)
            self.assertEqual(
                [
                    "diagram-crew-dark.svg",
                    "diagram-crew-light.svg",
                    "diagram-crew.svg",
                    "diagram-loop-dark.svg",
                    "diagram-loop-light.svg",
                    "diagram-loop.svg",
                ],
                names,
            )
            for path in written:
                with self.subTest(file=path.name):
                    self.assertNotIn(b"\r\n", path.read_bytes())


if __name__ == "__main__":
    unittest.main()
