#!/usr/bin/env python3
"""Maintain a generated index block inside a folder's MEMORY.md.

This script OWNS one block, delimited by the two HTML markers below. Everything
between them is rewritten on each run; **everything outside them is preserved
byte-for-byte**. The block body is one `- [<name>](<file.md>) — <description>`
line per note directly in the target folder (non-recursive), sorted by filename.
Link text is the note's frontmatter `name`; a note wanting a different index
label should set `name` accordingly.

Adopting a marker-less file (issue #102). A `MEMORY.md` that predates the
markers is replaced by the block **only** when every non-blank line in it is
byte-identical to a line this run would emit (see `_is_safely_replaceable`).
Anything else — prose, headings, hand-annotated bullets, links into
subdirectories — makes the file "not ours": the block is appended, nothing is
removed, and a `⚠` line says so.

De-duplication. The generated block omits any note whose file is already linked
in the text outside the markers, so appending a block to a hand-maintained list
does not double it. This applies on every path, always.

Malformed markers. When the block's extent is unknowable — a begin without an
end, an end without a begin, reversed markers, or duplicates — the file is left
untouched and the run exits 2. Appending would duplicate the block on every
subsequent run; truncating could delete prose. A human resolves it.

Exit codes:
    0  up-to-date, written, or skipped (no notes and no index file)
    1  stale (`--check` only — nothing is ever written under `--check`)
    2  malformed markers; refusing to write (in both modes)

Usage:
    python scripts/wiki_index.py --dir memory/concepts
    python scripts/wiki_index.py --store operational --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _wiki_common import REPO_DIR, iter_notes, load_stores

# Markers delimiting the block this script OWNS. Everything between them is
# rewritten on each run; everything outside is left byte-for-byte alone.
# Namespaced to match `readiness:generated` (compute_readiness.py:95-96).
GENERATED_BEGIN = "<!-- memory-index:generated start -->"
GENERATED_END = "<!-- memory-index:generated end -->"

_BLOCK_NOTICE = (
    "<!-- Generated by scripts/wiki_index.py. Edits between these markers are\n"
    "     overwritten; everything outside them is preserved. -->"
)

# Block bodies for the two cases where there is nothing to list. The block is
# still written in both: the markers are what make the next run splice in place
# instead of appending a second block.
NO_NOTES_BODY = "_(no notes yet)_"
ALL_LINKED_BODY = "_(every note in this folder is already linked above)_"

# Markdown link targets. Duplicates `wiki_lint._MDLINK_RE:25` on purpose: moving
# the shared wiki vocabulary into `_wiki_common.py` is D3, deferred to the
# follow-up issue, and this PR leaves `_wiki_common.py` and `wiki_lint.py`
# untouched. Consolidate the two when D3 lands.
_LINKED_TARGET_RE = re.compile(r"\]\(([^)]+\.md)\)")

_CHECK_DETAIL = {
    "created": "no index file; run without --check to create one",
    "spliced": "generated block differs; run without --check to regenerate",
    "migrated": "no index markers; run without --check to adopt them",
    "appended": (
        "no index markers; run without --check to append a block "
        "— hand-written content is preserved"
    ),
}

_WROTE_DETAIL = {
    "created": "created",
    "spliced": "regenerated block",
    "migrated": "adopted index markers",
    "appended": "appended a generated block; hand-written content preserved",
}


def build_index(dir_path: Path) -> str:
    lines: list[str] = []
    for p, fm, _ in iter_notes(dir_path, recursive=False):
        name = str(fm.get("name") or p.stem)
        desc = str(fm.get("description") or "")
        lines.append(f"- [{name}]({p.name}) — {desc}" if desc else f"- [{name}]({p.name})")
    return "\n".join(lines) + ("\n" if lines else "")


def render_block(body: str) -> str:
    """The owned block: markers, the explanatory notice, and `body` between them.

    `body` carries no trailing newline. Deterministic in `body` alone — nothing
    here reads the clock, so a second run on unchanged input is byte-identical.
    Always uses `\\n`; splicing an LF block into a CRLF file yields mixed endings
    once, and run 2 reads the LF block back and compares equal.
    """
    return (
        f"{GENERATED_BEGIN}\n"
        f"\n"
        f"{_BLOCK_NOTICE}\n"
        f"\n"
        f"{body}\n"
        f"\n"
        f"{GENERATED_END}\n"
    )


def _classify_markers(text: str) -> tuple[str, str]:
    """Classify a file's markers as `none` / `ok` / `malformed` (D7).

    Counts first, and only takes positions once the counts prove there is
    exactly one of each. `compute_readiness.compose()` (:388-398) tests marker
    *presence* and splices with `.index()`, so a begin marker with no end falls
    to its append branch and duplicates the block on every run. Refusing is the
    deliberate improvement over that precedent: with a begin and no end the
    block's extent is unknowable — appending duplicates, truncating at EOF may
    delete prose — so a human resolves it.

    Returns (kind, reason); `reason` is "" unless the kind is `malformed`.
    """
    begins = text.count(GENERATED_BEGIN)
    ends = text.count(GENERATED_END)
    if begins == 0 and ends == 0:
        return "none", ""
    if begins > 1:
        return "malformed", f"{begins} begin markers"
    if ends > 1:
        return "malformed", f"{ends} end markers"
    if ends == 0:
        return "malformed", "begin marker without an end marker"
    if begins == 0:
        return "malformed", "end marker without a begin marker"
    if text.index(GENERATED_END) < text.index(GENERATED_BEGIN):
        return "malformed", "end marker before begin marker"
    return "ok", ""


def _block_span(text: str) -> tuple[int, int]:
    """(start, stop) of the owned block, including its own trailing newline.

    Only valid once `_classify_markers` has returned `ok`.
    """
    start = text.index(GENERATED_BEGIN)
    stop = text.index(GENERATED_END) + len(GENERATED_END)
    if text[stop:stop + 2] == "\r\n":
        stop += 2
    elif text[stop:stop + 1] == "\n":
        stop += 1
    return start, stop


def outside_block(text: str) -> str:
    """Everything in `text` that is not the owned block — the preserved content.

    Only valid once `_classify_markers` has returned `ok`.
    """
    start, stop = _block_span(text)
    return text[:start] + text[stop:]


def _is_safely_replaceable(existing_text: str, emitted_lines: set[str]) -> bool:
    """True iff every non-blank line of `existing_text` is a line this run emits.

    **Shape matching is not sufficient.** The first draft of this fix asked
    "does this line *look* generated" with a regex. This line passes such a
    regex, and passes a link-target containment check too, yet is unambiguously
    hand-written::

        - [START HERE — read before touching sessions](auth-model.md) — ask Markus first

    `[^\\]]*` swallows the annotation, `— .*` swallows the note, and
    `auth-model.md` is a target the generator does emit — so shape matching
    silently flattens it to the plain generated bullet and the human's warning
    is gone. The safety question is not "does this look like a generated line",
    it is "is this **the** line I would generate". Hence set membership against
    the emitted lines, byte-for-byte.

    Line identity is also the *only* thing that saves a file with no prose at
    all. In `ai-os#138`, `repo/soulsgate-payment/MEMORY.md` was pure bullets —
    no headings, no orientation text, nothing a prose check could catch. It
    survives here solely because its bullets link `adr/….md` targets that a
    non-recursive walk of the folder never emits, so at least one line fails
    membership and the file takes the append path.

    **Accepted, stated loss: hand-curated ordering is not preserved.** This is a
    set test, so a file whose lines are all generated lines but deliberately
    reordered *is* replaced, and comes back in generator order. Ordering is the
    only thing this predicate can lose, and only in a file that contains nothing
    but generated lines. Documented in `memory/CONVENTIONS.md`.

    `str.splitlines()` handles `\\n`, `\\r\\n` and `\\r`, so a CRLF
    pure-generated file still migrates.
    """
    return all(
        line in emitted_lines
        for line in existing_text.splitlines()
        if line.strip()
    )


def _linked_targets(text: str) -> set[str]:
    """Every `.md` link target in `text`, with a leading `./` stripped."""
    return {
        m.group(1)[2:] if m.group(1).startswith("./") else m.group(1)
        for m in _LINKED_TARGET_RE.finditer(text)
    }


def dedupe_body(lines: list[str], preserved: str) -> list[str]:
    """Drop bullets whose note is already linked in the preserved text (D13/D14).

    Without this, appending a block to a hand-maintained list of 27 bullets
    produces those 27 bullets plus a generated block re-listing the same notes.
    `memory/` is what agents read as ground truth; a doubled index is a
    correctness regression landing on exactly the files this fix exists to
    protect.

    `preserved` is **everything outside the markers**, on every path — append
    and splice alike (D14). If de-duplication ran only on append, run 2 would
    take the splice path, put the full note list back, and the doubling would
    return.

    Matching is exact string comparison on the link target. Both failure
    directions are safe: a miss produces a duplicate bullet (noisy,
    non-destructive), and a spurious hit omits a bullet for a note the file
    demonstrably already links.
    """
    already = _linked_targets(preserved)
    if not already:
        return list(lines)
    return [line for line in lines if not (_linked_targets(line) & already)]


def compose(
    existing_text: str | None, block: str, *, replaceable: bool
) -> tuple[str | None, str]:
    """Merge `block` into `existing_text`; `None` means "write nothing".

    Returns (new_text_or_None, disposition) where disposition is one of
    `created` / `spliced` / `migrated` / `appended` / `malformed:<reason>`.
    `replaceable` is consulted only for a marker-less file, and comes from
    `_is_safely_replaceable`.

    Idempotent: feeding the result back in produces the same text again.
    """
    if existing_text is None:
        return block, "created"

    kind, reason = _classify_markers(existing_text)
    if kind == "malformed":
        return None, f"malformed:{reason}"

    if kind == "ok":
        start, stop = _block_span(existing_text)
        return existing_text[:start] + block + existing_text[stop:], "spliced"

    if replaceable:
        return block, "migrated"

    prefix = existing_text
    if prefix and not prefix.endswith(("\n", "\r")):
        prefix += "\n"
    return prefix + "\n" + block, "appended"


def regenerate(dir_path: Path, *, check: bool = False) -> tuple[int, list[str]]:
    """Bring `dir_path/MEMORY.md`'s generated block up to date.

    Returns (rc, summary_lines). Never raises on a malformed file — it returns
    rc 2 and a `⚠` summary line, so `promote_learnings.py`'s unattended call
    site surfaces the condition instead of swallowing an exception.
    """
    index_path = dir_path / "MEMORY.md"
    emitted_lines = [line for line in build_index(dir_path).splitlines() if line.strip()]

    # newline="" on read AND write disables universal-newline translation, so the
    # comparison is against what is actually on disk and "\n" is never expanded
    # to os.linesep on Windows (issues #83/#84; the apply_theme.py:83-97 pattern).
    existing = (
        index_path.read_text(encoding="utf-8", newline="")
        if index_path.exists()
        else None
    )

    # D15: no notes and no index file — create nothing.
    if not emitted_lines and existing is None:
        return 0, [f"skipped (no notes): {index_path}"]

    kind, reason = _classify_markers(existing or "")
    if kind == "malformed":
        return 2, [
            f"⚠ malformed index markers: {index_path} ({reason}); refusing to write"
        ]

    replaceable = existing is None or _is_safely_replaceable(existing, set(emitted_lines))

    # D14: `preserved` is everything the run will keep, on every path.
    if existing is None:
        preserved = ""
    elif kind == "ok":
        preserved = outside_block(existing)
    elif replaceable:
        preserved = ""  # the whole file is about to be replaced by the block
    else:
        preserved = existing

    if not emitted_lines:
        body = NO_NOTES_BODY
    else:
        kept = dedupe_body(emitted_lines, preserved)
        body = "\n".join(kept) if kept else ALL_LINKED_BODY

    new_text, disposition = compose(existing, render_block(body), replaceable=replaceable)
    if new_text is None:  # defensive — the malformed case is caught above
        return 2, [
            f"⚠ malformed index markers: {index_path} "
            f"({disposition.partition(':')[2]}); refusing to write"
        ]

    if new_text == existing:
        return 0, [f"up-to-date: {index_path}"]
    if check:
        return 1, [f"stale: {index_path} ({_CHECK_DETAIL[disposition]})"]

    index_path.write_text(new_text, encoding="utf-8", newline="")
    summary = [f"wrote: {index_path} ({_WROTE_DETAIL[disposition]})"]
    if disposition == "appended":
        summary.append(
            f"⚠ appended a generated block to {index_path} — it had no index markers "
            f"and content that is not ours. Nothing was removed; the existing "
            f"hand-maintained list was preserved and the generated block covers only "
            f"the notes it did not already link."
        )
    return 0, summary


def _resolve_dir(args: argparse.Namespace) -> Path | None:
    if args.dir:
        return (REPO_DIR / args.dir).resolve()
    stores = load_stores()
    store = stores.get(args.store)
    if not store:
        return None
    path = store.get("path")
    return (REPO_DIR / path).resolve() if path else None


def main() -> int:
    # Summary lines carry — and ⚠; a legacy Windows console defaults to cp1252 and
    # would raise UnicodeEncodeError. Guarded — a redirected StringIO in tests has
    # no reconfigure. Placed ahead of _resolve_dir so it also covers the error
    # print on the resolve-failure path.
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, ValueError):
        pass

    ap = argparse.ArgumentParser(description="Regenerate a folder's MEMORY.md index.")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--dir", help="folder (relative to repo root) to index")
    g.add_argument("--store", help="store name from stores.json")
    ap.add_argument("--check", action="store_true", help="exit 1 if stale; write nothing")
    args = ap.parse_args()

    dir_path = _resolve_dir(args)
    if dir_path is None or not dir_path.is_dir():
        print(f"error: could not resolve a directory (dir={args.dir!r} store={args.store!r})")
        return 1
    rc, summary = regenerate(dir_path, check=args.check)
    for line in summary:
        print(line)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
