#!/usr/bin/env python3
"""Maintain a generated index block inside a folder's MEMORY.md.

This script OWNS one block, delimited by the two HTML markers below. Everything
between them is rewritten on each run; **everything outside them is preserved
byte-for-byte**. The block body is one `- [<name>](<file.md>) — <description>`
line per note directly in the target folder (non-recursive), sorted by filename.
Link text is the note's frontmatter `name`; a note wanting a different index
label should set `name` accordingly.

Marker recognition is **line-anchored and fence-aware**. A marker counts only
when it is the whole content of its line (leading/trailing spaces and tabs
aside) and that line is not inside a fenced code block. A `MEMORY.md` may
therefore document the convention — quote both markers in a sentence, or show
the block in a ```-fenced example — without the generator treating the quoted
text as its own block and deleting everything between the two mentions.

Adopting a marker-less file (issue #102). A `MEMORY.md` that predates the
markers is replaced by the block **only** when every non-blank line in it is
byte-identical to a line this run would emit (see `_is_safely_replaceable`).
Anything else — prose, headings, hand-annotated bullets, links into
subdirectories — makes the file "not ours": the block is appended, nothing is
removed, and a `⚠` line says so.

De-duplication. The generated block omits any note whose file is already linked
in the text outside the markers, so appending a block to a hand-maintained list
does not double it. This applies on every path, always.

Malformed markers. When the block's extent is unknowable — a begin without an
end, an end without a begin, reversed markers, or duplicates — the file is left
untouched and the run exits 2. Appending would duplicate the block on every
subsequent run; truncating could delete prose. A human resolves it. `compose()`
is the single classification authority: it is the only place that decides to
refuse, and `regenerate()` derives its rc 2 from `compose()` returning `None`.

Exit codes:
    0  up-to-date, written, or skipped (no notes and no index file)
    1  stale (`--check` only — nothing is ever written under `--check`)
    2  malformed markers; refusing to write (in both modes)

Usage:
    python scripts/wiki_index.py --dir memory/concepts
    python scripts/wiki_index.py --store operational --check
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from _wiki_common import REPO_DIR, iter_notes, load_stores

# Markers delimiting the block this script OWNS. Everything between them is
# rewritten on each run; everything outside is left byte-for-byte alone.
# Namespaced to match `readiness:generated` (compute_readiness.py:95-96).
GENERATED_BEGIN = "<!-- memory-index:generated start -->"
GENERATED_END = "<!-- memory-index:generated end -->"

_BLOCK_NOTICE = (
    "<!-- Generated by scripts/wiki_index.py. Edits between these markers are\n"
    "     overwritten; everything outside them is preserved. -->"
)

# Block bodies for the two cases where there is nothing to list. The block is
# still written in both: the markers are what make the next run splice in place
# instead of appending a second block.
NO_NOTES_BODY = "_(no notes yet)_"
ALL_LINKED_BODY = "_(every note in this folder is already linked above)_"

# Markdown link targets. Duplicates `wiki_lint._MDLINK_RE:25` on purpose: moving
# the shared wiki vocabulary into `_wiki_common.py` is D3, deferred to the
# follow-up issue, and this PR leaves `_wiki_common.py` and `wiki_lint.py`
# untouched. Consolidate the two when D3 lands.
_LINKED_TARGET_RE = re.compile(r"\]\(([^)]+\.md)\)")

# A marker counts only as a **whole line** — spaces and tabs around it, nothing
# else on it. Built from the constants above so the two can never drift apart.
#
# The first version of this fix scanned for the markers as bare substrings
# anywhere in the file. A curated `MEMORY.md` that merely *mentions* both
# markers in one sentence — the shape `memory/CONVENTIONS.md` teaches downstream
# users to write — then classified `ok`, and the words between the two mentions
# were spliced away silently, at rc 0, with no ⚠. That is issue #102's own
# failure class re-entering through its fix, so recognition is anchored.
_MARKER_LINE_RE = re.compile(
    r"^[ \t]*(?:(?P<start>{})|(?P<end>{}))[ \t]*$".format(
        re.escape(GENERATED_BEGIN), re.escape(GENERATED_END)
    )
)

# An opening or closing code fence: three or more backticks or tildes, indented
# or not, plus whatever follows on the line (an info string, or — for a closing
# fence — nothing). Hand-rolled rather than parsed: ADR 0001 is stdlib-only, and
# fence state is the only markdown context these two scans need.
_FENCE_RE = re.compile(r"^[ \t]*(`{3,}|~{3,})(.*)$")


def _split_lines(text: str) -> list[tuple[int, int, str]]:
    """`[(start, stop, line)]`, where `stop` is past the line's terminator.

    `str.splitlines(keepends=True)` splits on `\\n`, `\\r\\n` and `\\r`, and
    keeping the ends makes the accumulated offsets exact — so a span derived
    from them is byte-faithful under every line ending, with no per-ending
    arithmetic at the call site.
    """
    out: list[tuple[int, int, str]] = []
    pos = 0
    for line in text.splitlines(keepends=True):
        out.append((pos, pos + len(line), line))
        pos += len(line)
    return out


def _fenced_line_indices(lines: list[tuple[int, int, str]]) -> set[int]:
    """Indices of the lines inside a **closed** fenced code block, fences included.

    An unclosed fence is deliberately *not* treated as opening a region.
    CommonMark runs it to the end of the document; doing that here would hide a
    real trailing block from `_classify_markers` on every run, so the file would
    classify `none`, take the append path, and grow a fresh block every time —
    the duplicate-forever bug D7 exists to prevent. Between "an unterminated
    fence hides the block forever" and "an unterminated fence is not a fence",
    only the second is non-destructive.
    """
    fenced: set[int] = set()
    open_at: int | None = None
    open_char = ""
    open_run = 0
    for i, (_, _, raw) in enumerate(lines):
        m = _FENCE_RE.match(raw.rstrip("\r\n"))
        if not m:
            continue
        char, run, rest = m.group(1)[0], len(m.group(1)), m.group(2)
        if open_at is None:
            open_at, open_char, open_run = i, char, run
        elif char == open_char and run >= open_run and not rest.strip():
            fenced.update(range(open_at, i + 1))
            open_at = None
    return fenced


def _marker_lines(text: str) -> list[tuple[str, int, int]]:
    """`[(kind, start, stop)]` for every marker line, in document order.

    `kind` is `start` or `end`; `start`/`stop` bound the whole line **including
    its terminator**. Lines inside a fenced code block are skipped, so a fenced
    example documenting the block shape is not mistaken for the block itself.
    HTML comments are deliberately *not* skipped — the markers are HTML
    comments, so skipping those would blind this scan to its own subject.
    """
    lines = _split_lines(text)
    fenced = _fenced_line_indices(lines)
    out: list[tuple[str, int, int]] = []
    for i, (start, stop, raw) in enumerate(lines):
        if i in fenced:
            continue
        m = _MARKER_LINE_RE.match(raw.rstrip("\r\n"))
        if m:
            out.append(("start" if m.group("start") else "end", start, stop))
    return out


def _strip_html_comments(text: str) -> str:
    """`text` with every `<!-- … -->` replaced by a single space.

    An unterminated `<!--` blanks the rest of the text, the way a browser reads
    it. For the one caller (`_linked_targets`) that direction fails toward a
    duplicate bullet — noisy, non-destructive — rather than toward a real note
    silently missing from the index.
    """
    out: list[str] = []
    pos = 0
    while True:
        begin = text.find("<!--", pos)
        if begin < 0:
            out.append(text[pos:])
            return "".join(out)
        out.append(text[pos:begin])
        end = text.find("-->", begin + 4)
        if end < 0:
            return "".join(out)
        out.append(" ")
        pos = end + 3

_CHECK_DETAIL = {
    "created": "no index file; run without --check to create one",
    "spliced": "generated block differs; run without --check to regenerate",
    "migrated": "no index markers; run without --check to adopt them",
    "appended": (
        "no index markers; run without --check to append a block "
        "— hand-written content is preserved"
    ),
}

_WROTE_DETAIL = {
    "created": "created",
    "spliced": "regenerated block",
    "migrated": "adopted index markers",
    "appended": "appended a generated block; hand-written content preserved",
}


def build_index(dir_path: Path) -> str:
    lines: list[str] = []
    for p, fm, _ in iter_notes(dir_path, recursive=False):
        name = str(fm.get("name") or p.stem)
        desc = str(fm.get("description") or "")
        lines.append(f"- [{name}]({p.name}) — {desc}" if desc else f"- [{name}]({p.name})")
    return "\n".join(lines) + ("\n" if lines else "")


def render_block(body: str) -> str:
    """The owned block: markers, the explanatory notice, and `body` between them.

    `body` carries no trailing newline. Deterministic in `body` alone — nothing
    here reads the clock, so a second run on unchanged input is byte-identical.
    Always uses `\\n`; splicing an LF block into a CRLF file yields mixed endings
    once, and run 2 reads the LF block back and compares equal.
    """
    return (
        f"{GENERATED_BEGIN}\n"
        f"\n"
        f"{_BLOCK_NOTICE}\n"
        f"\n"
        f"{body}\n"
        f"\n"
        f"{GENERATED_END}\n"
    )


def _classify_markers(text: str) -> tuple[str, str]:
    """Classify a file's markers as `none` / `ok` / `malformed` (D7).

    Counts first, and only compares positions once the counts prove there is
    exactly one of each. `compute_readiness.compose()` (:388-398) tests marker
    *presence* and splices with `.index()`, so a begin marker with no end falls
    to its append branch and duplicates the block on every run. Refusing is the
    deliberate improvement over that precedent: with a begin and no end the
    block's extent is unknowable — appending duplicates, truncating at EOF may
    delete prose — so a human resolves it.

    Counting and position-finding both go through `_marker_lines`, so the two
    can never disagree about what is a marker — a disagreement would mean
    classifying `ok` on one span and splicing another.

    Returns (kind, reason); `reason` is "" unless the kind is `malformed`.
    """
    markers = _marker_lines(text)
    begins = [m for m in markers if m[0] == "start"]
    ends = [m for m in markers if m[0] == "end"]
    if not begins and not ends:
        return "none", ""
    if len(begins) > 1:
        return "malformed", f"{len(begins)} begin markers"
    if len(ends) > 1:
        return "malformed", f"{len(ends)} end markers"
    if not ends:
        return "malformed", "begin marker without an end marker"
    if not begins:
        return "malformed", "end marker without a begin marker"
    if ends[0][1] < begins[0][1]:
        return "malformed", "end marker before begin marker"
    return "ok", ""


def _block_span(text: str) -> tuple[int, int]:
    """(start, stop) of the owned block, including its own trailing newline.

    Only valid once `_classify_markers` has returned `ok`. The bounds are whole
    marker *lines*, so the end marker's terminator — `\\n`, `\\r\\n` or a lone
    `\\r` — is consumed by construction rather than by per-ending arithmetic.
    """
    markers = _marker_lines(text)
    start = next(m for m in markers if m[0] == "start")[1]
    stop = next(m for m in markers if m[0] == "end")[2]
    return start, stop


def outside_block(text: str) -> str:
    """Everything in `text` that is not the owned block — the preserved content.

    Only valid once `_classify_markers` has returned `ok`.
    """
    start, stop = _block_span(text)
    return text[:start] + text[stop:]


def _is_safely_replaceable(existing_text: str, emitted_lines: set[str]) -> bool:
    """True iff every non-blank line of `existing_text` is a line this run emits.

    **Shape matching is not sufficient.** The first draft of this fix asked
    "does this line *look* generated" with a regex. This line passes such a
    regex, and passes a link-target containment check too, yet is unambiguously
    hand-written::

        - [START HERE — read before touching sessions](auth-model.md) — ask Markus first

    `[^\\]]*` swallows the annotation, `— .*` swallows the note, and
    `auth-model.md` is a target the generator does emit — so shape matching
    silently flattens it to the plain generated bullet and the human's warning
    is gone. The safety question is not "does this look like a generated line",
    it is "is this **the** line I would generate". Hence set membership against
    the emitted lines, byte-for-byte.

    `ai-os#138`'s `repo/soulsgate-payment/MEMORY.md` is a genuine regression
    guard, and line identity does reject it. It was pure bullets — no headings,
    no orientation text, nothing a *prose* check could catch — and it survives
    here because its bullets link `adr/….md` targets that a non-recursive walk
    of the folder never emits, so at least one line fails membership and the
    file takes the append path.

    It is **not**, however, what makes the case for line identity. Mutation
    testing showed the rejected shape+containment predicate rejects that file
    too, and for the same reason: containment catches `adr/0001-x.md` unaided.
    The `START HERE` line above is the one shape that actually discriminates
    between the two predicates — there the target *is* emitted, so containment
    passes and only byte-identity notices the human's annotation. Keep both
    cases covered, but do not cite `soulsgate-payment` as the argument for line
    identity over containment; it does not distinguish them.

    **Accepted, stated loss: hand-curated ordering is not preserved.** This is a
    set test, so a file whose lines are all generated lines but deliberately
    reordered *is* replaced, and comes back in generator order. Ordering is the
    only thing this predicate can lose, and only in a file that contains nothing
    but generated lines. Documented in `memory/CONVENTIONS.md`.

    `str.splitlines()` handles `\\n`, `\\r\\n` and `\\r`, so a CRLF
    pure-generated file still migrates.
    """
    return all(
        line in emitted_lines
        for line in existing_text.splitlines()
        if line.strip()
    )


def _link_scan_text(text: str) -> str:
    """`text` with fenced code blocks and HTML comments blanked out.

    Fenced lines keep only their terminator and comments collapse to a space, so
    offsets shift but line structure does not — this feeds a regex, nothing that
    reports positions.
    """
    lines = _split_lines(text)
    fenced = _fenced_line_indices(lines)
    kept = [
        raw[len(raw.rstrip("\r\n")):] if i in fenced else raw
        for i, (_, _, raw) in enumerate(lines)
    ]
    return _strip_html_comments("".join(kept))


def _linked_targets(text: str) -> set[str]:
    """Every `.md` link target in `text`, with a leading `./` stripped.

    Matches inside a fenced code block or an HTML comment do not count. D13
    accepts a spurious hit on the grounds that it "omits a bullet for a note the
    file demonstrably already links" — and the plan's Open Question 1 extends
    that to a prose mention, since the file does link it. Neither holds for an
    illustrative link in a fenced example or a commented-out
    `<!-- TODO: drop the old [alpha](a.md) note -->`: there the file does not
    link the note at all, so suppressing it makes the index lie by omission.
    `wiki_lint._memory_referenced` (`wiki_lint.py:39-46`) is fooled by the same
    text, so nothing else would surface the resulting orphan either.
    """
    return {
        m.group(1)[2:] if m.group(1).startswith("./") else m.group(1)
        for m in _LINKED_TARGET_RE.finditer(_link_scan_text(text))
    }


def dedupe_body(lines: list[str], preserved: str) -> list[str]:
    """Drop bullets whose note is already linked in the preserved text (D13/D14).

    Without this, appending a block to a hand-maintained list of 27 bullets
    produces those 27 bullets plus a generated block re-listing the same notes.
    `memory/` is what agents read as ground truth; a doubled index is a
    correctness regression landing on exactly the files this fix exists to
    protect.

    `preserved` is **everything outside the markers**, on every path — append
    and splice alike (D14). If de-duplication ran only on append, run 2 would
    take the splice path, put the full note list back, and the doubling would
    return.

    Matching is exact string comparison on the link target — case-sensitive, and
    after stripping a leading `./`. Both failure directions are safe: a miss
    produces a duplicate bullet (noisy, non-destructive), and a spurious hit
    omits a bullet for a note the file demonstrably already links. Links inside
    fenced code or HTML comments are not links the file makes, and do not count
    — see `_linked_targets`.
    """
    already = _linked_targets(preserved)
    if not already:
        return list(lines)
    return [line for line in lines if not (_linked_targets(line) & already)]


def compose(
    existing_text: str | None, block: str, *, replaceable: bool
) -> tuple[str | None, str]:
    """Merge `block` into `existing_text`; `None` means "write nothing".

    Returns (new_text_or_None, disposition) where disposition is one of
    `created` / `spliced` / `migrated` / `appended` / `malformed:<reason>`.
    `replaceable` is consulted only for a marker-less file, and comes from
    `_is_safely_replaceable`.

    Idempotent: feeding the result back in produces the same text again.
    """
    if existing_text is None:
        return block, "created"

    kind, reason = _classify_markers(existing_text)
    if kind == "malformed":
        return None, f"malformed:{reason}"

    if kind == "ok":
        start, stop = _block_span(existing_text)
        return existing_text[:start] + block + existing_text[stop:], "spliced"

    if replaceable:
        return block, "migrated"

    prefix = existing_text
    if prefix and not prefix.endswith(("\n", "\r")):
        prefix += "\n"
    return prefix + "\n" + block, "appended"


def regenerate(dir_path: Path, *, check: bool = False) -> tuple[int, list[str]]:
    """Bring `dir_path/MEMORY.md`'s generated block up to date.

    Returns (rc, summary_lines). Never raises on a malformed file — `compose`
    returns `None`, this returns rc 2 and a `⚠` summary line, so
    `promote_learnings.py`'s unattended call site surfaces the condition instead
    of swallowing an exception.
    """
    index_path = dir_path / "MEMORY.md"
    emitted_lines = [line for line in build_index(dir_path).splitlines() if line.strip()]

    # newline="" on read AND write disables universal-newline translation, so the
    # comparison is against what is actually on disk and "\n" is never expanded
    # to os.linesep on Windows (issues #83/#84; the apply_theme.py:83-97 pattern).
    existing = (
        index_path.read_text(encoding="utf-8", newline="")
        if index_path.exists()
        else None
    )

    # D15: no notes and no index file — create nothing.
    if not emitted_lines and existing is None:
        return 0, [f"skipped (no notes): {index_path}"]

    # `compose` is the single classification authority — the malformed refusal
    # lives there and nowhere else (see the `new_text is None` branch below).
    # This call reads the classification only to pick which text the run will
    # preserve; it makes no decision to refuse, so the two cannot desynchronise
    # into "classified ok here, refused there".
    kind, _ = _classify_markers(existing or "")
    replaceable = existing is None or _is_safely_replaceable(existing, set(emitted_lines))

    # D14: `preserved` is everything the run will keep, on every path.
    if existing is None:
        preserved = ""
    elif kind == "ok":
        preserved = outside_block(existing)
    elif kind == "none" and replaceable:
        preserved = ""  # the whole file is about to be replaced by the block
    else:
        # Curated marker-less content, or a malformed file whose body `compose`
        # is about to discard along with everything else it composed.
        preserved = existing

    if not emitted_lines:
        body = NO_NOTES_BODY
    else:
        kept = dedupe_body(emitted_lines, preserved)
        body = "\n".join(kept) if kept else ALL_LINKED_BODY

    new_text, disposition = compose(existing, render_block(body), replaceable=replaceable)
    if new_text is None:  # D7: the one and only refusal path
        return 2, [
            f"⚠ malformed index markers: {index_path} "
            f"({disposition.partition(':')[2]}); refusing to write"
        ]

    if new_text == existing:
        return 0, [f"up-to-date: {index_path}"]
    if check:
        return 1, [f"stale: {index_path} ({_CHECK_DETAIL[disposition]})"]

    index_path.write_text(new_text, encoding="utf-8", newline="")
    summary = [f"wrote: {index_path} ({_WROTE_DETAIL[disposition]})"]
    if disposition == "appended":
        summary.append(
            f"⚠ appended a generated block to {index_path} — it had no index markers "
            f"and content that is not ours. Nothing was removed; the existing "
            f"hand-maintained list was preserved and the generated block covers only "
            f"the notes it did not already link."
        )
    return 0, summary


def _resolve_dir(args: argparse.Namespace) -> Path | None:
    if args.dir:
        return (REPO_DIR / args.dir).resolve()
    stores = load_stores()
    store = stores.get(args.store)
    if not store:
        return None
    path = store.get("path")
    return (REPO_DIR / path).resolve() if path else None


def main() -> int:
    # Summary lines carry — and ⚠; a legacy Windows console defaults to cp1252 and
    # would raise UnicodeEncodeError. Guarded — a redirected StringIO in tests has
    # no reconfigure. Placed ahead of _resolve_dir so it also covers the error
    # print on the resolve-failure path.
    try:
        sys.stdout.reconfigure(encoding="utf-8")  # type: ignore[union-attr]
    except (AttributeError, ValueError):
        pass

    ap = argparse.ArgumentParser(description="Regenerate a folder's MEMORY.md index.")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--dir", help="folder (relative to repo root) to index")
    g.add_argument("--store", help="store name from stores.json")
    ap.add_argument("--check", action="store_true", help="exit 1 if stale; write nothing")
    args = ap.parse_args()

    dir_path = _resolve_dir(args)
    if dir_path is None or not dir_path.is_dir():
        print(f"error: could not resolve a directory (dir={args.dir!r} store={args.store!r})")
        return 1
    rc, summary = regenerate(dir_path, check=args.check)
    for line in summary:
        print(line)
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
